# variables
variables:
  GITLAB_REPO: "https://gitlab.com/Andr1500/cicd_bluegreen_codepipeline_ecs.git"
  CODECOMMIT_REPO: "ssh://git-codecommit.eu-central-1.amazonaws.com/v1/repos/from_gitlab"
  REPO_DIR: cicd_bluegreen_codepipeline_ecs
  BRANCH: deploy_to_codecommit

stages:
  - test
  - deploy

#run test
run_tests:
  stage: test
  image: python:3.9-slim-buster
  before_script: #set up necessary dependencies
    - apt-get update && apt-get install make
  script:
    - make test


# Clone repo from Gitlab to Codecommit
push_to_codecommit:
  stage: deploy
  before_script:
    - mkdir ~/.ssh/
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa git-codecommit.eu-central-1.amazonaws.com >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host git-codecommit.*.amazonaws.com\n  User $AWS_SSH_USER\n  PreferredAuthentications publickey\n  IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
    - rm -rf ~/.git
    - git clone -b $BRANCH $GITLAB_REPO
    - cd $REPO_DIR/
  script:
    - git push  $CODECOMMIT_REPO --all
