#variables
variables:
  GITLAB_REPO: "https://gitlab.com/Andr1500/CICD_flask_app_with_BlueGreen.git"
  CODECOMMIT_REPO: "ssh://git-codecommit.eu-central-1.amazonaws.com/v1/repos/from_gitlab"
  REPO_DIR: CICD_flask_app_with_BlueGreen
  BRANCH: deploy_to_codecommit

#Clone repo from Gitlab to Codecommit
push_to_codecommit:
    stage: deploy
    before_script:
        - mkdir ~/.ssh/
        - chmod 700 ~/.ssh
        - ssh-keyscan -t rsa git-codecommit.eu-central-1.amazonaws.com >> ~/.ssh/known_hosts
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - echo -e "Host git-codecommit.*.amazonaws.com\n  User $AWS_SSH_USER\n  PreferredAuthentications publickey\n  IdentityFile ~/.ssh/id_rsa" > ~/.ssh/config
        - rm -rf ~/.git
        - git clone -b $BRANCH $GITLAB_REPO
        - cd $REPO_DIR/
    script:
        - git push  $CODECOMMIT_REPO --all
