#variables
variables:
  DOCKER_REGISTRY: 138161713046.dkr.ecr.eu-central-1.amazonaws.com
  AWS_DEFAULT_REGION: eu-central-1
  IMAGE_NAME: python-app
  APP_NAME: python-app
  IMAGE_TAG: python-app-1.0
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

#run test
run_tests:
  image: python:3.9-slim-buster #we need this image because default docker image is Ruby based on
  before_script: #set up necessary dependencies
    - apt-get update && apt-get install make
  script:
    - make test

#build docker image and push it to private repo
build_image:
  image: 
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
    - docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$CI_PIPELINE_IID .
    - docker push $DOCKER_REGISTRY/$IMAGE_NAME:$CI_PIPELINE_IID