#run test
run_tests:
  image: python:3.9-slim-buster #we need this image because default docker image is Ruby based on
  before_script: #set up necessary dependencies
    - apt-get update && apt-get install make
    # - apt-get install -y amazon-ecr-credential-helper
    # - pip install awscliv2
  script:
    - make test

#build docker image and push it to private repo
build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - pip install awscliv2
    - awsv2 ecr get-login --region eu-central-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.eu-central-1.amazonaws.com
  # script:
  #   - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  #   - docker push $IMAGE_NAME:$IMAGE_TAG